name: Feed Database

on:
  workflow_dispatch:  # Manual trigger

jobs:
  import-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Upload the Auctions_Data.bacpac file from the db folder to the storage container
      - name: Upload Auctions_Data.bacpac to Azure Storage
        run: |
          az storage blob upload \
            --account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
            --container-name db \
            --name Auctions_Data.bacpac \
            --file db/Auctions_Data.bacpac \
            --sas-token "${{ secrets.STORAGE_SAS_TOKEN }}"

      # Import the bacpac file into the SQL Database
      - name: Import bacpac into SQL Database
        run: |
          az sql db import \
            --admin-user sqladmin \
            --admin-password ${{ secrets.ADMIN_PASSWORD }} \
            --name sqldb-calicot-dev-5 \
            --server sqlsrv-calicot-dev-5 \
            --storage-uri "https://${{ secrets.STORAGE_ACCOUNT_NAME }}.blob.core.windows.net/db/Auctions_Data.bacpac?${{ secrets.STORAGE_SAS_TOKEN }}"
